In [21]:
import numpy as np

In [109]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [112]:
b = np.array([(1.5,2,3), (4,5,6)]),
print(b)

(array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]]),)


In [113]:
 c = np.array([[(1.5,2,3), (4,5,6)],[(3,2,1), (4,5,6)]]),
print(c)

(array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]]),)


In [114]:
np.save("my_array", a)

In [115]:
np.savez('array.npz', a, b)

In [116]:
np.load('my_array.npy')

array([1, 2, 3])

In [117]:

np.save("myfile.txt", a)


In [118]:
np.load("myfile.txt.npy")

array([1, 2, 3])

In [75]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


In [119]:
a.shape

(3,)

In [120]:
len(a)

3

In [121]:
a.ndim

1

In [122]:
a.size

3

In [123]:
 g = a - b

In [124]:
print(g)

[[[-0.5  0.   0. ]
  [-3.  -3.  -3. ]]]


In [125]:
print(g)

[[[2.5 4.  6. ]
  [5.  7.  9. ]]]


In [126]:
w = a * b
print(w)

[[[ 1.5  4.   9. ]
  [ 4.  10.  18. ]]]


In [127]:
r = a/b
print (r)

[[[0.66666667 1.         1.        ]
  [0.25       0.4        0.5       ]]]


In [128]:
a.sum()

6

In [129]:
a.min()

1

In [130]:
a.max(axis=0)

3

In [131]:
a.mean()

2.0

In [132]:
np.median(a)

2.0

In [133]:
np.std(b)

1.5920810978785667

In [134]:
h = a. view

In [135]:
print(h)

<built-in method view of numpy.ndarray object at 0x000002785C2EFF30>


In [136]:
np.copy(a)

array([1, 2, 3])

In [137]:
h = a.copy()

In [138]:
a.sort()

In [139]:
a.sort(axis=0)

In [158]:
a[2]

3

In [163]:
b[0]

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [154]:
b[0]

In [155]:
print(h)

[[1 2 3 0 0 0]
 [0 0 0 0 0 0]]


In [147]:
np.append(h,g)

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [148]:
np.delete(a,[1])

array([1, 3])